mutualPeers:
  - consensusNode: "consensus-validator-1"
  - peers:
      - nodeName: "da-bridge-1-0"
        containerName: "da"
      - nodeName: "da-full-1-0"
        containerName: "da"
  - peers:
      - nodeName: "da-bridge-2-0"
        containerName: "da"
      - nodeName: "da-full-2-0"
        containerName: "da"
    trustedPeersPath: "/home/celestia/config"