#extensions:
#  basicauth/otlp:
#    client_auth:
#      username: <uid>
#      # TODO: use a secret manager!
#      password: "XYZ"

receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'torch'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8080']

exporters:
  otlphttp:
#    auth:
#      authenticator: basicauth/otlp
    endpoint:  https://otlp-gateway-prod-us-central-0.grafana.net/otlp

processors:
  batch:

service:
#  extensions: [basicauth/otlp]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      processors: [batch]