apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
  - name: ghcr.io/jrmanes/torch
    newTag: latest
  - name: otel/opentelemetry-collector-contrib
    newTag: 0.71.0

configMapGenerator:
- name: config
  files:
  - ./config/config.yaml
- name: otel-agent
  files:
  #- ./config/otel-agent.yaml
  - ./config/otel-agent-celestia.yaml
